### ISSUE TITLE
FB Prophet against others

### ISSUE THREAD

**Issue by MuaazBin** [MaxBenChrist/awesome_time_series_in_python#11]
Sorry to ask a question using issue.
You have a tremendous article on time series analysis.  Please, may you suggest a tool/python library preferably that works well for predicting a number of cars on the street at hourly level. 
Right now I am using FbProphet, the predictions are off by 20% (MAPE). Trying to predict one week into the future.

**Comment by MaxBenChrist** [comment]
either look for papers on google scholar that deal with the issue and take their methods or compare different ml pipelines
