### ISSUE TITLE
Updated time series software list

### ISSUE THREAD

**Issue by mloning** [MaxBenChrist/awesome_time_series_in_python#18]
Hi, I took the liberty to update your list of time series related software and copy it into our wiki [here]( https://github.com/alan-turing-institute/sktime/wiki/Related-software), hope that's okay, of course feel free to include any of my changes into your list (I'm happy to work on this list together, but PRs seemed a little too complicated for that).

**Comment by MaxBenChrist** [comment]
Hi Markus, happy that you like it and thanks for giving credit. 

Regarding PR: you can just edit the list in your browser here on github. No need to checkout the repo locally etc. After you are done, github will create an pr for you.
