### ISSUE TITLE
Add traces library

### ISSUE THREAD

**Issue by Ogaday** [MaxBenChrist/awesome_time_series_in_python#2]
First of all, looks like a great resource - definitely some libraries I haven't seen before, thanks.

I think [traces](https://github.com/datascopeanalytics/traces) would fit very well here. From the docs:

> A Python library for unevenly-spaced time series analysis.

**Comment by MaxBenChrist** [comment]
Thanks for the compliment.

Yes, lets add traces to the list.

Shall I edit it or do you want to do a PR? You can edit the file in your browser!
