### ISSUE TITLE
pyFTS: Fuzzy Time Series for Python

### ISSUE THREAD

**Issue by petroniocandido** [MaxBenChrist/awesome_time_series_in_python#23]
Hi,

I would humbly like to ask you to include my library pyFTS on your awesome list. pyFTS is a free and open-source library for Fuzzy Time Series in Python programming language. Here follow some materials about it:
- Digital Object Identifier: https://doi.org/10.5281/zenodo.597359
- Official site and documentation: https://pyfts.github.io/pyFTS/
- Code repository and issue tracking: https://github.com/PYFTS/pyFTS
- PhD Thesis on Fuzzy Time Series: https://doi.org/10.5281/zenodo.3374641 
- A short tutorial on Fuzzy Time Series:
Part I: Introduction to the Fuzzy Logic, Fuzzy Time Series and the pyFTS library (https://towardsdatascience.com/a-short-tutorial-on-fuzzy-time-series-dcc6d4eb1b15)

Part II: High order, weighted and multivariate methods and a case study of solar energy forecasting. (https://towardsdatascience.com/a-short-tutorial-on-fuzzy-time-series-part-ii-with-an-case-study-on-solar-energy-bda362ecca6d )

Part III: Interval and probabilistic forecasting, non-stationary time series, concept drifts and time variant models. (https://towardsdatascience.com/a-short-tutorial-on-fuzzy-time-series-part-iii-69445dff83fb)

More example codes: https://github.com/PYFTS/notebooks

Please do not hesitate to get in touch and ask any questions. Thanks in advance.

**Comment by mloning** [comment]
Out of curiosity, do you have any comparative benchmarking results on the M4 study or so?

**Comment by petroniocandido** [comment]
@mloning Not yet, but it is an excellent suggestion!

**Comment by MaxBenChrist** [comment]
Sure, @petroniocandido, just submit a pr against this repo with the addition of pyFTS
