### ISSUE TITLE
where to find repo  for multivariate time series classification or regression 

### ISSUE THREAD

**Issue by Sandy4321** [MaxBenChrist/awesome_time_series_in_python#29]
great material  thanks
may you clarify : 
where to find repo  for multivariate time series classification or regression  
1 
  where all values are continues values 
2
or  even will it work for multivariate time series where values are mixture of continues  and categorical values
for example 2 dimensions have continues values and 3 dimensions are categorical values

    color        weight     gender  height  age  
1    black       56              m          160    34
2    white       77              f            170    54
3    yellow      87             m          167     43
4    white       55             m            198    72
5   white       88              f            176     32

**Comment by ricardovvargas** [comment]
@Sandy4321, it seams that 3W dataset can help you. https://github.com/ricardovvargas/3w_dataset/

**Comment by Sandy4321** [comment]
great thanks
only there is no code
https://www.kaggle.com/afrniomelo/3w-dataset/notebooks
https://archive.ics.uci.edu/ml/datasets/3W+dataset

any ideas for code for  multivariate time series .
1
where all values are continues values
2
or even will it work for multivariate time series where values are mixture of continues and categorical values
for example 2 dimensions have continues values and 3 dimensions are categorical values

color weight gender height age
1 black 56 m 160 34
2 white 77 f 170 54
3 yellow 87 m 167 43
4 white 55 m 198 72
5 white 88 f 176 32

**Comment by MaxBenChrist** [comment]
not sure if this is the right place to ask here, maybe try stack overvflow?
