### ISSUE TITLE
Add Arrow library

### ISSUE THREAD

**Issue by Ogaday** [MaxBenChrist/awesome_time_series_in_python#3]
[Arrow](https://github.com/crsmithdev/arrow) would also fit quite nicely here, in the general timestamps & dates handling category. From the docs:

> Arrow is a Python library that offers a sensible, human-friendly approach to creating, manipulating, formatting and converting dates, times, and timestamps. It implements and updates the datetime type, plugging gaps in functionality, and provides an intelligent module API that supports many common creation scenarios. Simply put, it helps you work with dates and times with fewer imports and a lot less code.

**Comment by MaxBenChrist** [comment]
Good point, shall I edit it or do you want to do a PR? You can edit the file in your browser!

**Comment by Ogaday** [comment]
I'm happy to do PRs :) I can add them to the Libraries box? Is it worth organising the packages by theme yet? (ie. munging dates, ts feature extraction, ts modelling, etc).

**Comment by MaxBenChrist** [comment]
> I'm happy to do PRs :) I can add them to the Libraries box? Is it worth organising the packages by theme yet? (ie. munging dates, ts feature extraction, ts modelling, etc).

Looking forward to the prs :). 

Please feel free to propose any order. As long as each subtable has at least 2-3 items I think it is fine. We can later easily reorganize the items
