### ISSUE TITLE
Find generators for synthetic time series data sets

### ISSUE THREAD

**Issue by WGierke** [MaxBenChrist/awesome_time_series_in_python#7]
Thanks a lot for this _awesome_ repo ;)
I only found a few data sets that include time series data.
Do you know a way to artificially generate time series data?
That'd be incredibly helpful.
Thanks a lot!
Willi

**Comment by MaxBenChrist** [comment]
Hi Willi, 

In my package tsfresh we have some Methode to generare artificial time series, please have a look at https://github.com/blue-yonder/tsfresh/tree/master/tsfresh/examples

**Comment by WGierke** [comment]
Thank you @MaxBenChrist for your very fast reply. I even stared that repo a long time ago! I should have definitely taken a closer look back then. :)
