### ISSUE TITLE
Link Suggestion

### ISSUE THREAD

**Issue by rlshuhart** [MaxBenChrist/awesome_time_series_in_python#9]
Thanks for organizing the time series packages in python. Here is one that is fascinating to me regarding time to event prediction. I'll let you be the judge if this qualifies for your list.

https://github.com/ragulpr/wtte-rnn/

**Comment by MaxBenChrist** [comment]
Thanks for the great link @rlshuhart. I enjoyed reading the blogpost.

Indeed, I would like to add wtte-rrn to this list. You want to submit a pr?

**Comment by rlshuhart** [comment]
PR submitted 33ab98f
